"""empty message

Revision ID: 4460b350d592
Revises: 
Create Date: 2020-08-03 12:05:31.331719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4460b350d592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('height', sa.Integer(), nullable=True))
    op.execute("UPDATE product SET height = 8")
    op.alter_column('product', 'height', existing_type=sa.Integer(), nullable=False)

    op.add_column('product', sa.Column('length', sa.Integer(), nullable=True))
    op.execute("UPDATE product SET length = 20")
    op.alter_column('product', 'length', existing_type=sa.Integer(), nullable=False)

    op.add_column('product', sa.Column('width', sa.Integer(), nullable=True))
    op.execute("UPDATE product SET width = 15")
    op.alter_column('product', 'width', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'width')
    op.drop_column('product', 'length')
    op.drop_column('product', 'height')
    # ### end Alembic commands ###
